# Generated by Django 5.0.6 on 2024-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.TextField(default=''),
        ),
    ]
